app/views.py
from flask import Blueprint, render_template, current_app, redirect, url_for, \
    request, after_this_request
from auth.forms import ExtendedConfirmRegisterForm, ExtendedRegisterForm
from flask.ext.security import current_user
from forms import CommuteSearchForm
from models import CommuteSearch
import markdown
import os
from .carpool.views import get_lat_lng_box
from .persistence import get_db, get_cache
import logging
import datetime
import base64
from htmlmin.main import minify

main = Blueprint("main", __name__)
db = get_db()
cache = get_cache()
_logger = logging.getLogger("rideshare")


def _save_and_fetch_searches(search_form):
    distance = 15*1609
    search = CommuteSearch(
        start_area=search_form.start_locality.data+", "+search_form.start_state.data,
        end_area=search_form.end_locality.data+", "+search_form.end_state.data,
        start_address=search_form.start_address.data,
        end_address=search_form.end_address.data,
        start_latitude=search_form.start_latitude.data,
        start_longitude=search_form.start_longitude.data,
        end_latitude=search_form.end_latitude.data,
        end_longitude=search_form.end_longitude.data,
        datetime=datetime.datetime.utcnow()
    )

    start_lat_rng, start_lng_rng = get_lat_lng_box(search.start_latitude,
                                                   search.start_longitude,
                                                   distance)
    end_lat_rng, end_lng_rng = get_lat_lng_box(search.end_latitude,
                                               search.end_longitude,
                                               distance)

    result = CommuteSearch.query.filter(CommuteSearch.start_latitude.between(*start_lat_rng),
                                    CommuteSearch.start_longitude.between(*start_lng_rng),
                                    CommuteSearch.end_latitude.between(*end_lat_rng),
                                    CommuteSearch.end_longitude.between(*end_lng_rng)).limit(10).all()

    self_location = [{"start": [search.start_latitude, search.start_longitude],
                      "end": [search.end_latitude, search.end_longitude],
                      "content": "Your search",
                      "type": "self"
                      }]
    locations = self_location + [{"start": [c.start_latitude, c.start_longitude],
                                  "end": [c.end_latitude, c.end_longitude],
                                  'content': str("%s to %s" % (c.start_area, c.end_area)),
                                  'type': "other"} for i, c in enumerate(result)]

    try:
        db.session.add(search)
        db.session.commit()
    except Exception as e:
        _logger.exception(str(e))
    return result, locations


@cache.memoize(timeout=500)
def _render_index(is_authenticated):
    security = current_app.extensions["security"]
    search_form = CommuteSearchForm()
    if security.confirmable:
        register_user_form = ExtendedConfirmRegisterForm()
    else:
        register_user_form = ExtendedRegisterForm()
    #blogging = current_app.extensions["FLASK_BLOGGING_ENGINE"]
    #posts = blogging.storage.get_posts(count=5, recent=True)

    img_data = None
    file_name = os.path.join(current_app.static_folder, "img", "city_street_sm2.jpg" )
    with open(file_name, "rb") as imageFile:
        img_data = base64.b64encode(imageFile.read())

    html = render_template("index.html",
                           register_user_form=register_user_form,
                           search_form=search_form,
                           img_data=img_data)
    html_min = minify(html)
    return html_min


@main.route("/", methods=["GET"])
def index():
    view = _render_index(current_user.is_authenticated())
    return view


@main.route("/peek/", methods=["GET", "POST"])
def search():
    search_form = CommuteSearchForm()
    search_result=None
    locations=None
    if request.method == "POST":
        if search_form.validate_on_submit():
            search_result, locations = _save_and_fetch_searches(search_form)

    return render_template("search.html",
                           search_form=search_form,
                           search_result=search_result,
                           locations=locations)


@cache.cached(timeout=60)
def _render_tou():
    md = markdown.Markdown()
    f = open(os.path.join(current_app.template_folder, "terms_of_use.md"))
    text = f.read()
    f.close()
    content = md.convert(text)
    return content


@main.route("/tou/")
def terms_of_use():
    content = _render_tou()
    return render_template("terms_of_use.html", content=content)

app/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}

<h2>Menu</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Login</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Register</a></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">Forgot password</a></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">Confirm account</a></li>
  {% endif %}
</ul>

{% endif %}

app/templates/security/base.html
{% extends 'base.html' %}
{% block page %}
<div class="container" role="main">
    {% include "_message.html" %}
    <div class="row">
        <div class="col-md-3">
            {% block sidecontent %}
            {% include "security/_menu.html" %}
            {% endblock sidecontent %}
        </div>
        <div class="col-md-9">
            {% block maincontent %}

            {% endblock maincontent %}
        </div>
    </div>
</div>
{% endblock page %}

app/templates/security/change_password.html
{% extends 'carpool/base.html' %}
{% block title %} {{config.SITENAME}} - Change Password {% endblock %}
{% from "_macros.html" import render_field_with_errors, render_field_safe %}
{% block maincontent %}
<div class="profile-content">
    <h2>Change password</h2>
    <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <form action="{{ url_for_security('change_password') }}"
              method="POST"
              name="change_password_form">
            {{ change_password_form.hidden_tag() }}

            <div class="form-group">
                <div class="col-md-12">
                    {{ render_field_with_errors( change_password_form.password,
                    class="form-control", placeholder="Current Password")}}<br>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    {{ render_field_with_errors( change_password_form.new_password,
                    class="form-control", placeholder="New Password")}}<br>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    {{ render_field_with_errors( change_password_form.new_password_confirm,
                    class="form-control", placeholder="Confirm New Password")}}<br>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    {{ render_field_safe(change_password_form.submit, class="btn btn-success") }}
                </div>
            </div>
        </form>
    </div>
    </div>
</div>
{% endblock maincontent %}

app/templates/security/forgot_password.html
{% extends 'security/base.html' %}
{% block title %} {{config.SITENAME}} - Forgot Password {% endblock %}
{% from "_macros.html" import render_field_with_errors, render_field_safe %}

{% block maincontent %}
<div id="signupbox" style="margin-top:25px"  class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Forgot Password</div>
        </div>
        <div class="panel-body">
            <form action="{{ url_for('security.forgot_password') }}" method="POST" name="forgot_password_form">
                {{ forgot_password_form.hidden_tag() }}
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors( forgot_password_form.email,class="form-control", placeholder="Email")}}<br>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_safe(forgot_password_form.submit, class="btn btn-success") }}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock maincontent %}

app/templates/security/login_user.html
{% extends 'security/base.html' %}
{% block title %} {{config.SITENAME}} - Login {% endblock %}
{% from "_macros.html" import render_field_with_errors, render_field_safe %}

{% block maincontent %}
<div id="signupbox" style="margin-top:25px"  class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Sign In</div>
        </div>
        <div class="panel-body">
            <form action="{{ url_for('security.login') }}" method="POST" name="login_user_form">
                {{ login_user_form.hidden_tag() }}
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors( login_user_form.email,class="form-control", placeholder="Email")}}<br>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors( login_user_form.password,
                        class="form-control", placeholder="Password")}}<br>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_safe(login_user_form.submit, class="btn btn-success") }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 control">
                        <div style="margin-top:10px; border-top: 1px solid#888; padding-top:10px;">
                            {% if config.SECURITY_RECOVERABLE %}
                            <span class="pull-left"><a href="{{ url_for('security.forgot_password') }}"><small>Forgot password?</small></a></span>
                            {% endif %}

                            {%  if config.SECURITY_REGISTERABLE %}
                            <span class="pull-right"><a href="{{ url_for('security.register') }}"><small>Not a member yet?</small></a></span>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock maincontent %}

app/templates/security/register_user.html
{% extends 'security/base.html' %}

{% block title %}  {{config.SITENAME}} - Register{% endblock %}
{% from "_macros.html" import render_field_safe, render_field_with_errors %}
{% block maincontent %}
<div id="signupbox" style="margin-top:25px"  class="col-sm-8 col-sm-offset-2">
    <div class="panel  panel-info">
        <div class="panel-heading">
            <div class="panel-title">Register</div>
        </div>
        <div class="panel-body">
            <form action="{{ url_for_security('register') }}"
                  method="POST" class="form-horizontal" role="form" name="register_user_form">
                {{register_user_form.hidden_tag()}}
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors( register_user_form.name,
                        class="form-control", placeholder="How should we call you?" )}}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors( register_user_form.email,
                        class="form-control", placeholder="How can we reach you?" )}}
                    </div>
                </div>
                <div class="form-group">
                    <dt>
                        <label class="col-md-2 control-label" for="gender">Gender</label>
                    </dt>
                    <dd>
                        <div class="col-md-9 col-md-offset-1">
                            {% for subfield in register_user_form.gender %}
                            <label class="radio-inline" for="{{ subfield.label.field_id }}">
                                {{  render_field_safe(subfield) }}
                                {{ subfield.label.text }}
                            </label>
                            {% endfor %}
                        </div>
                    </dd>
                    {% if register_user_form.gender.errors %}
                    <ul>
                        {% for error in register_user_form.gender.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors( register_user_form.password,
                        class="form-control", placeholder="How do we know its you?")}}
                    </div>
                </div>
                {% if register_user_form.password_confirm %}
                <div class="form-group">
                    <div class="col-md-12">
                        {{ render_field_with_errors(register_user_form.password_confirm,
                        class="form-control", placeholder="Confirming! If it is one of those days, you know!") }}
                    </div>

                </div>
                {% endif %}

                <div class="form-group">
                    <div class="col-md-12">
                        By registering you accept to the <a href="{{ url_for('main.terms_of_use')}}">terms of use</a><br>
                        {{ render_field_safe(register_user_form.submit, class="btn btn-success") }}

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 control">
                        <div style="margin-top:10px; border-top: 1px solid#888; padding-top:10px;">
                            <span class="pull-left"><a href="{{ url_for('security.login') }}"><small>Already a member?</small></a></span>

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/security/send_confirmation.html
{% extends 'security/base.html' %}
{% block title %} {{config.SITENAME}} - Password Confirmation {% endblock %}
{% from "_macros.html" import render_field_with_errors, render_field %}
{% block maincontent %}
    <div id="signupbox"  style="margin-top:25px;"  class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Resend Confirmation Instructions</div>
            </div>
            <div class="panel-body">

                <form action="{{ url_for_security('send_confirmation') }}" method="POST" name="send_confirmation_form">
                    {{ send_confirmation_form.hidden_tag() }}
                    {{ render_field_with_errors(send_confirmation_form.email, class="form-control", placeholder="Email") }}
                    {{ render_field(send_confirmation_form.submit, value="Send", class="btn btn-success") }}
                </form>
            </div>
        </div>
    </div>
{% endblock maincontent %}