app/views.py
from flask import Blueprint, render_template, current_app, redirect, url_for, \
    request, after_this_request
from auth.forms import ExtendedConfirmRegisterForm, ExtendedRegisterForm
from flask.ext.security import current_user
from forms import CommuteSearchForm
from models import CommuteSearch
import markdown
import os
from .carpool.views import get_lat_lng_box
from .persistence import get_db, get_cache
import logging
import datetime
import base64
from htmlmin.main import minify

main = Blueprint("main", __name__)
db = get_db()
cache = get_cache()
_logger = logging.getLogger("rideshare")


def _save_and_fetch_searches(search_form):
    distance = 15*1609
    search = CommuteSearch(
        start_area=search_form.start_locality.data+", "+search_form.start_state.data,
        end_area=search_form.end_locality.data+", "+search_form.end_state.data,
        start_address=search_form.start_address.data,
        end_address=search_form.end_address.data,
        start_latitude=search_form.start_latitude.data,
        start_longitude=search_form.start_longitude.data,
        end_latitude=search_form.end_latitude.data,
        end_longitude=search_form.end_longitude.data,
        datetime=datetime.datetime.utcnow()
    )

    start_lat_rng, start_lng_rng = get_lat_lng_box(search.start_latitude,
                                                   search.start_longitude,
                                                   distance)
    end_lat_rng, end_lng_rng = get_lat_lng_box(search.end_latitude,
                                               search.end_longitude,
                                               distance)

    result = CommuteSearch.query.filter(CommuteSearch.start_latitude.between(*start_lat_rng),
                                    CommuteSearch.start_longitude.between(*start_lng_rng),
                                    CommuteSearch.end_latitude.between(*end_lat_rng),
                                    CommuteSearch.end_longitude.between(*end_lng_rng)).limit(10).all()

    self_location = [{"start": [search.start_latitude, search.start_longitude],
                      "end": [search.end_latitude, search.end_longitude],
                      "content": "Your search",
                      "type": "self"
                      }]
    locations = self_location + [{"start": [c.start_latitude, c.start_longitude],
                                  "end": [c.end_latitude, c.end_longitude],
                                  'content': str("%s to %s" % (c.start_area, c.end_area)),
                                  'type': "other"} for i, c in enumerate(result)]

    try:
        db.session.add(search)
        db.session.commit()
    except Exception as e:
        _logger.exception(str(e))
    return result, locations


@cache.memoize(timeout=500)
def _render_index(is_authenticated):
    security = current_app.extensions["security"]
    search_form = CommuteSearchForm()
    if security.confirmable:
        register_user_form = ExtendedConfirmRegisterForm()
    else:
        register_user_form = ExtendedRegisterForm()
    #blogging = current_app.extensions["FLASK_BLOGGING_ENGINE"]
    #posts = blogging.storage.get_posts(count=5, recent=True)

    img_data = None
    file_name = os.path.join(current_app.static_folder, "img", "city_street_sm2.jpg" )
    with open(file_name, "rb") as imageFile:
        img_data = base64.b64encode(imageFile.read())

    html = render_template("index.html",
                           register_user_form=register_user_form,
                           search_form=search_form,
                           img_data=img_data)
    html_min = minify(html)
    return html_min


@main.route("/", methods=["GET"])
def index():
    view = _render_index(current_user.is_authenticated())
    return view


@main.route("/peek/", methods=["GET", "POST"])
def search():
    search_form = CommuteSearchForm()
    search_result=None
    locations=None
    if request.method == "POST":
        if search_form.validate_on_submit():
            search_result, locations = _save_and_fetch_searches(search_form)

    return render_template("search.html",
                           search_form=search_form,
                           search_result=search_result,
                           locations=locations)


@cache.cached(timeout=60)
def _render_tou():
    md = markdown.Markdown()
    f = open(os.path.join(current_app.template_folder, "terms_of_use.md"))
    text = f.read()
    f.close()
    content = md.convert(text)
    return content


@main.route("/tou/")
def terms_of_use():
    content = _render_tou()
    return render_template("terms_of_use.html", content=content)

app/templates/_macros.html
{% macro render_field_with_errors(field) %}
  <p>
    <dt>{{ field.label }} </dt>
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    </dd>
  </p>
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

{% macro render_field_safe(field) %}
  {{ field(**kwargs)|safe }}
{% endmacro %}

app/templates/_menu.html
{% if security.registerable or security.recoverable or security.confirmabled %}
<h2>Menu</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}">Login</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}">Register</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">Forgot password</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">Confirm account</a></li>
  {% endif %}
</ul>
{% endif %}

app/templates/_message.html
{% block message %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endwith %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}
    {% endblock meta %}



    <title>{% block title %}{{config.SITENAME}}{%block extratitle %}-Greater Los Angeles Carpool & Rideshare Community{% endblock extratitle %}{% endblock title %}</title>


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">



    {% block extrastyle %} {% endblock extrastyle %}
    <link href="/static/css/style.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/">
                <img alt="Brand" src="/static/img/logo.png" style="height:100%">
            </a>
        </div>
        {% block navright %}

        <div class="collapse navbar-collapse pull-right">

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{{ url_for('blogging.index') }}">Blog</a>
                </li>
                {% if current_user.is_authenticated() %}
                <li>
                    <a href="{{ url_for('carpool.index') }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for_security('logout') }}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{{ url_for('main.search') }}">Search</a>
                </li>
                <li>
                    <a href="{{ url_for_security('login') }}">Login</a>
                </li>
                <li>
                    <a href="{{ url_for_security('register') }}">Register</a>
                </li>
                {% endif %}
            </ul>

        </div><!--/.nav-collapse -->

        {% endblock navright %}
    </div>
</div>
{% block page %}

{% endblock page %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{%  block js %}
<script src="/static/js/jquery-2.1.4.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
{% endblock js %}
{% block extrajs %} {% endblock extrajs %}
{% if not config.DEBUG %}
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-65320718-1', 'auto');
    ga('send', 'pageview');
</script>
{% endif %}
</body>
</html>

app/templates/search.html
{% extends 'base.html' %}
{% from "_macros.html" import render_field_safe, render_field_with_errors %}
{% block page %}
<div class="container">
    <h2>Recent Searches</h2>

    <div class="row text-center">
        <form action="{{ url_for('main.search')}}" method="POST" class="form"
              role="form" name="search_form">
            {{ search_form.hidden_tag() }}
            <div class="form-group">
                <div class="col-md-4 col-md-offset-1">
                {{ render_field_safe(search_form.start_address, class="form-control",
                placeholder="Start Address", required=true) }}
                    </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    {{ render_field_safe(search_form.end_address, class="form-control",
                placeholder="End Address", required=true) }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2">
                    {{ render_field_safe(search_form.submit, class="btn btn-warning") }}
                </div>
            </div>
            <div id="startDetails">
                {{ search_form.start_latitude(dataGeoStart="lat", type="hidden" )  }}
                {{ search_form.start_longitude(dataGeoStart="lng", type="hidden")  }}
                {{ search_form.start_locality(dataGeoStart="locality", type="hidden") }}
                {{ search_form.start_state(dataGeoStart="administrative_area_level_1", type="hidden") }}
            </div>
            <div id="endDetails">
                {{ search_form.end_latitude(dataGeoEnd="lat", type="hidden")  }}
                {{ search_form.end_longitude(dataGeoEnd="lng", type="hidden")  }}
                {{ search_form.end_locality(dataGeoEnd="locality", type="hidden") }}
                {{ search_form.end_state(dataGeoEnd="administrative_area_level_1", type="hidden") }}
            </div>
        </form>
    </div>
    <br>
    {% if search_result and search_result | length %}
        <span >Please <a href="{{ url_for_security('register') }}">register</a> to contact other carpoolers.</span>
        <br>
    <div id="mapCanvas" style="width:100%; height:300px;"> </div>
    <br>

    {% for search_row in search_result | batch(2) %}
    <div class="row">
        {% for s in search_row %}
        <div class="col-md-6">
            <li class="list-group-item">
                <span>{{s.start_area}} to {{ s.end_area }} (id:{{ s.id }})</span>
            </li>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock page %}

{% block extrajs %}
{% include "carpool/_search_script.html" %}
<script src="/static/js/jquery.geocomplete.min.js"></script>
<script>
    $("#start_address").geocomplete({ details: "form", detailsAttribute: "dataGeoStart" }).bind();
    $("#end_address").geocomplete({ details: "form", detailsAttribute: "dataGeoEnd" }).bind();
</script>
{% endblock extrajs %}

app/templates/terms_of_use.html
{%  extends "base.html" %}
{% block extratitle %} - Terms Of Use{% endblock extratitle %}
{% block page %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {{ content | safe }}
        </div>
    </div>
{%  endblock page %}